version: "3.8"

services:
    web:
        image: php:8.1-apache
        restart: always
        container_name: apache_php
        volumes:
            - ./project:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - db
    
    db:
        image: mariadb:latest
        restart: always
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        
volumes:
    project:
